#!/bin/bash
input="$@"
regex_hasprotocol='^(https?|ftp|file)://[^\s\\]*$'
regex_noprotocol='^([A-Za-z0-9]+\.)+[A-Za-z0-9]+$'

MAGENTA=$(tput setaf 5)
NORMAL=$(tput sgr0)

if [[ "$input" =~ "$regex_hasprotocol" ]] ; then
	MESSAGE="OPENING"
	echo "$MAGENTA$MESSAGE$NORMAL: $input"
	lynx "$input"
elif [[ "$input" =~ "$regex_noprotocol" ]]; then
	MESSAGE="OPENING"
	echo "$MAGENTA$MESSAGE$NORMAL: https://$input"
	lynx "https://$input"
else
  MESSAGE="SEARCHING FOR"
	echo "$MAGENTA$MESSAGE$NORMAL: $input"
	lynx "https://duckduckgo.com/?q=${input// /%20}"
fi
