#!/bin/bash

main() {
	if [[ ! -d "$HOME/.local/boxes" ]]; then
		echo "No repository of sandboxes found. Creating repo directory"
		mkdir -p "$HOME/.local/boxes"
	fi

	if [[ "$#" == 0 ]]; then
		echo "No box name given." 
		echo "Create a <box-name> under \"$HOME/.local/boxes/\"."
		echo "In it create \`box.sh\` containg 3 functions - \`start\`, \`stop\` and \`enter\`."
		exit -1
	fi
	
	box_name="$1"
	if [[ ! -d "$HOME/.local/boxes/$box_name" ]]; then
		echo "[ERROR] Cannot find sandbox specification for '$box_name' in $HOME/.local/boxes/"
		exit -1
	fi

	box
}

box() {
	source "$HOME/.local/boxes/$box_name/box.sh"
	start
	enter
	stop
}

main "$@"
