#!/bin/bash
if ! pgrep -i Emacs > /dev/null; then 
	# Emacs UI is not running, start the daemon.
	emacs --daemon
fi

if [[ $(uname) =~ "Darwin" ]]; then
	emacsclient --create-frame $@
else
	emacsclient -nw --create-frame $@
fi
