#!/bin/bash

# A quick script for use with vim to add a splitter 
# line with a specific title.

# USAGE: In vim, run '.! htitle <title>' on the line 
# where you want this text.


echo "# ---------- $@ ----------"
