#!/bin/bash

source "$HOME/.gtdrc"

main() {
	if [[ -z "$1" ]] ; then
	    echo "ERROR: The first argument must be a project name under $PRJDIR"
	    exit 1
	fi

	prj="$1"
	shift

	check_prjdir "$prj"
	check_notesdir "$prj"

	# Use zettelkasten for capturing notes. 
  # 'note' is same as 'zet' for rest of the command syntax
	ZETDIR="$PRJDIR/$prj/notes" zet "$@"
}

# Check if project exists
check_prjdir() {
	if [[ ! -d "$PRJDIR/$1" ]] ; then
		read -p "Project directory - '$PRJDIR/$1', doesn't exist. Create [Y/n]? " MKPRJDIR
		if [[ "$MKPRJDIR" == "Y" ]] ; then
			echo "Creating $PRJDIR/$1"
			mkdir "$PRJDIR/$1"
		else
			echo "Cannot capture notes! Exiting."
			exit 1
		fi
	fi
}

# Check if notes exist
check_notesdir() {
	if [[ ! -d "$PRJDIR/$1/notes" ]] ; then
		read -p "Notes directory '$PRJDIR/$1/notes' doesn't exist. Create (Y/n)? " MKNOTEDIR
		if [[ $MKNOTEDIR == "Y" ]] ; then
			echo "Creating $PRJDIR/$1/notes"
			mkdir "$PRJDIR/$1/notes"
			git init "$PRJDIR/$1/notes"
		else
			echo "Cannot capture notes! Exiting."
			exit 1
		fi
	fi
}

####################
# entrypoint

main "$@"
