#!/bin/bash

source "$HOME/dotfiles/.gtdrc"


main() {
	if [[ -z "$1" ]] ; then
	    echo "ERROR: The first argument must be a project name under $PRJDIR"
	    exit 1
	fi

	prjdir="$1"

	check_prjdir "$1"
	check_notesdir "$1"

	# Use zettelkasten for capturing notes
	zet "$PRJDIR/$1/notes"
}

# Check if project exists
check_prjdir() {
	if [[ ! -d "$PRJDIR/$1" ]] ; then
		read -p "Project directory doesn't exist. Create [Y/n]? " MKPRJDIR
		if [[ "$MKPRJDIR" == "Y" ]] ; then
			echo "Creating $PRJDIR/$1"
			mkdir "$PRJDIR/$1"
			git init "$PRJDIR/$1"
		else
			echo "Cannot capture notes! Exiting."
			exit 1
		fi
	fi
}

# Check if notes exist
check_notesdir() {
	if [[ ! -d "$PRJDIR/$1/notes" ]] ; then
		read -p "Notes directory doesn't exist. Create (Y/n)? " MKNOTEDIR
		if [[ $MKNOTEDIR == "Y" ]] ; then
			echo "Creating $PRJDIR/$1/notes"
			mkdir "$PRJDIR/$1/notes"
		else
			echo "Cannot capture notes! Exiting."
			exit 1
		fi
	fi
}

####################
# entrypoint

main "$@"
