#!/bin/bash

# Colors
BOLD='\033[1;37;41m'
NC='\033[0m' # No Color

main() {
	if [[ "$1" == "list" ]] ; then
		taskpull projects
		exit
	fi

	PROJECT="$1"

	if [[ "$PROJECT" == "none" || "$PROJECT" == "" ]] ; then
		echo "Showing tasks that don't have a project..."
		PROJECT=""
	fi

	shift
	if [[ "$#" == "0" ]] ; then
		taskpull &>/dev/null
		echo ""; echo -e "${BOLD} TASKS ${NC}";
		task list project:"$PROJECT"
		echo ""; echo -e "${BOLD} WAITING ${NC}"
		task waiting project:"$PROJECT"
	else
		SUBCMD="$1"
		TASKID="$2"

		case "$SUBCMD" in 

			tickle)
				CONTAINS=$(does_prj_contain_task "$PROJECT" "$TASKID")
				if [[ "$CONTAINS" == "0" ]] ; then
					echo "Task-ID $TASKID not found in project \"$PROJECT\""
					exit
				fi
	
				tasksync "$TASKID" modify	wait:monday
				;;

			add)
				shift
				TASK="$@"
				tasksync "$SUBCMD" \"$TASK\" project:"$PROJECT"
				;;
		esac
	fi
}

does_prj_contain_task() {
	taskpull &>/dev/null
	FOUND=$(task list project:"$1" | grep "$2")
	if [[ "$FOUND" == "" ]] ; then
		FOUND=$(task waiting project:"$1" | grep "$2")
	fi

	if [[ "$FOUND" == "" ]] ;  then
		echo 0
	else
		echo 1
	fi
}

main "$@"

