#!/bin/bash

#  A simple script to add a task to the taskwarrior database to read and review
#  a webpage.
#
# Usage:
#		rnr https://www.example.com
#
#  Uses `wget` to download the webpage, `hxselect` to extract the title of the
#  webpage, and `task` to add the task to the taskwarrior database with the
#  title as the description and the link as an annotation. The task is tagged
#  with `+rnr` tag.

main() {
	prerequisites_check
	if [[ "$#" == "0" ]] ; then
		count=$(task count +rnr)
		if [[ "$count" -gt 10 ]]; then
			vit +rnr
		else
			taskpull list +rnr
		fi
	else
		read_n_review "$@"
	fi
}

prerequisites_check() {
	if ! command -v task &> /dev/null ; then
		echo "'taskwarrior' is not installed. Please install it first."
		exit 1
	fi
	if ! command -v hxselect &> /dev/null ; then
		echo "'HTML-XML-utils' is not installed. Please install it first."
		exit 1
	fi
	if ! command -v hxclean &> /dev/null ; then
		echo "'HTML-XML-utils' is not installed. Please install it first."
		exit 1
	fi
	if ! command -v vit &> /dev/null ; then
		echo "'vit' is not installed. Please install it first."
		exit 1
	fi

}

webpage_title() {
	wget -qO- "$*" | grep -oE '<title.*>.*<\/title>' |  hxclean | hxselect -i -c "title"
}

read_n_review() {
	link="$1"
	title=$(webpage_title "$link")
	descr="\"Read and review: $title\""
	id=$(task add +rnr "$descr" | sed -n 's/Created task \(.*\)./\1/p')
	task "$id" annotate "$link"
}

main "$@"
