#!/bin/bash

#  A simple script to add a reading link to an existing reading list file.
#
# Usage:
#		rnr https://www.example.com

source "$HOME/.gtdrc"

main() {
	prerequisites_check
	if [[ "$#" == "0" ]] ; then
	"$EDITOR" "$PRJDIR/reading-list.md"
	else
		read_n_review "$@"
	fi
}

prerequisites_check() {
	if ! command -v task &> /dev/null ; then
		echo "'taskwarrior' is not installed. Please install it first."
		exit 1
	fi
	if ! command -v hxselect &> /dev/null ; then
		echo "'HTML-XML-utils' is not installed. Please install it first."
		exit 1
	fi
	if ! command -v hxclean &> /dev/null ; then
		echo "'HTML-XML-utils' is not installed. Please install it first."
		exit 1
	fi
	if ! command -v vit &> /dev/null ; then
		echo "'vit' is not installed. Please install it first."
		exit 1
	fi
	if [[ ! -f "$PRJDIR/reading-list.md" ]]; then
		touch "$PRJDIR/reading-list.md"
		echo "# Reading List" >> "$PRJDIR/reading-list.md"
		echo "" >> "$PRJDIR/reading-list.md"
	fi
}

webpage_title() {
	wget -qO- "$*" | grep -oE '<title.*>.*<\/title>' |  hxclean | hxselect -i -c "title"
}

read_n_review() {
	link="$1"
	title=$(webpage_title "$link")
	echo "- [$title]($link)" >> "$PRJDIR/reading-list.md"
}

main "$@"
