#!/bin/bash

if [[ -z $SNIPDIR ]]; then 
	echo "\$SNIPDIR is undefined. Please set it in ~/.bashrc first." > /dev/stderr
	exit -1
fi
if [[ ! -d "$SNIPDIR" ]]; then
	echo "$SNIPDIR doesn't exist. Please create it and add one directory per category under it" > /dev/stderr
	exit -1
fi

if [[ ! -f "$SNIPDIR/$1.txt" ]]; then
	echo "Cannot find snippet '$1'. Please create file '$SNIPDIR/$1.txt'" > /dev/stderr
	exit -1
fi

snip() {
	SNIPPET="$SNIPDIR/$1.txt"
	cat "$SNIPPET"
}

snip "$@"



