#!/bin/bash


snip() {
	# Autocompletion
	[[ ! -z "$COMP_LINE" ]] && _snip && exit

	if [[ $# == 0 ]]; then
		echo "Missing snippet. Syntax - snip <path-to-snippet>" > /dev/stderr
		exit -1
	fi

	if [[ -z $SNIPDIR ]]; then 
		echo "\$SNIPDIR is undefined. Please set it in ~/.bashrc first." > /dev/stderr
		exit -1
	fi
	if [[ ! -d "$SNIPDIR" ]]; then
		echo "$SNIPDIR doesn't exist. Please create it and add one directory per category under it" > /dev/stderr
		exit -1
	fi

	if [[ ! -f "$SNIPDIR/$1" ]]; then
		echo "Cannot find snippet '$1'. Please create file '$SNIPDIR/$1" > /dev/stderr
		exit -1
	fi
	
	SNIPPET="$SNIPDIR/$1"
	cat "$SNIPPET"
}

_snip() {
	IFS=' ' read -r -a COMP_WORDS <<< "$COMP_LINE"
	if [[ -z "${COMP_WORDS[1]}" ]]; then
		cd "$SNIPDIR"
		for file in */**; do
			printf "$file\n"
		done
	else
		cd "$SNIPDIR"
		for file in "${COMP_WORDS[1]}"**; do
			if [[ -f "$file" ]]; then
				printf "$file\n"
			fi
		done
	fi
}

snip "$@"

