#!/bin/bash

source "$HOME/.gtdrc"

snip() {
	# Autocompletion
	[[ ! -z "$COMP_LINE" ]] && _snip && exit

	if [[ "$#" == 0 ]]; then
    echo "Missing snippet. Syntax - snip <path-to-snippet>" > /dev/stderr
		exit -1
	fi

	if [[ -z $SNIPDIR ]]; then 
		echo "\$SNIPDIR is undefined. Please set it in ~/.bashrc first." > /dev/stderr
		exit -1
	fi
	if [[ ! -d "$SNIPDIR" ]]; then
		echo "$SNIPDIR doesn't exist. Please create it and add one directory per category under it" > /dev/stderr
		exit -1
	fi

	if [[ ! -f "$SNIPDIR/$1" ]]; then
		echo "Cannot find snippet '$1'. Please create file '$SNIPDIR/$1" > /dev/stderr
		exit -1
	fi
	
	SNIPPET="$SNIPDIR/$1"
	cat "$SNIPPET"
}

_snip() {
	IFS=' ' read -r -a COMP_WORDS <<< "$COMP_LINE"
	# If the path already points to a file
	[[ -f "$SNIPDIR/${COMP_WORDS[1]}" ]] && exit

	cd "$SNIPDIR"
	find . -type f -print0 | while IFS= read -r -d '' file;
	do
		file="${file:2}"
		if [[ $file == *"${COMP_WORDS[1]}"* ]]; then
			echo "$file"
		fi
	done
}

snip "$@"

