#!/bin/bash

# waitfor - Mark a task as waiting for someone else to complete.
#
# Usage: waitfor [person] [task number]
#
# No arguments - show a list of tasks you are waiting on. Example - `waitfor`
# One argument - show a list of tasks you are waiting on a specific person. Example - `waitfor bob`
# Two arguments - mark a task (with given ID) as waiting for a person to complete. Example - `waitfor bob 3`. Also, set due date to next Monday and add a waiting tag.

if [[ "$#" == "0" ]] ; then
	# show list of waiting tasks
	echo "List of tasks you are waiting on..."
	task waiting
	exit
elif [[ "$#" == "1" ]] ; then
	person="$1"
	REDBACK=$(tput setab 1)
	BOLD=$(tput bold)
	WHITE=$(tput setaf 255)
	NORMAL=$(tput sgr0)
	echo -e "Waiting on: ${REDBACK}${WHITE}${BOLD}$person${NORMAL}.\n"
	task waiting owner:"$person"
	exit
else
	person="$1"
	taskid="$2"
	tasksync "$taskid" modify -in +waiting owner:"$person" due:+1w wait:monday
fi

