#!/bin/bash

# Simple script to extract weather information from wttr.in and show it in a single line (with emojis)

# Pull condition, temperature(actual & feels-like) and precipitation from wttr.in,
# convert it into a array
parts=($(curl -s http://wttr.in/Providence?format="%c+%t(%f)\n"))

condition="${parts[0]}"
temp="${parts[1]}"
precipitation=$(curl -s wttr.in | sed -n 7p)
echo "$condition  $temp"
